import 'package:Pluralsight/models/Course.dart';
import 'package:flutter/cupertino.dart';

class CourseListModel extends ChangeNotifier {
  final List<CourseModel> couserList = [
    new CourseModel(
        ID: 1,
        name: "Angular Fundamenttals",
        author: "Joe Eames",
        level: 1,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 150,
        category: 1),
    new CourseModel(
        ID: 2,
        name: "C# Fundamenttals",
        author: "Jim Wilson",
        level: 2,
        rating: 4.5,
        date: DateTime.now(),
        numberComment: 102,
        category: 1),
    new CourseModel(
        ID: 3,
        name: "Managing AWS Operation",
        author: "Brian Harison",
        level: 2,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 10,
        category: 1),
    new CourseModel(
        ID: 4,
        name: "Spring Framework",
        author: "Janaini Ravi",
        level: 2,
        rating: 4.5,
        date: DateTime.now(),
        numberComment: 110,
        category: 1),
    new CourseModel(
        ID: 5,
        name: "Spring: The Big Picture",
        author: "Eugene",
        level: 2,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 201,
        category: 2),
    new CourseModel(
        ID: 6,
        name: "Dependency Injection in APS.NET Core",
        author: "Nigel Poulton",
        level: 2,
        rating: 4.5,
        date: DateTime.now(),
        numberComment: 10,
        category: 2),
    new CourseModel(
        ID: 7,
        name: "Designing RESTful Web APIs",
        author: "Danial Lachance",
        level: 3,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 152,
        category: 3),
    new CourseModel(
        ID: 8,
        name: "Node.js: The big Picture",
        author: "Neil Morissey",
        level: 1,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 513,
        category: 2),
    new CourseModel(
        ID: 9,
        name: "Architecting for Reliablility on AWS",
        author: "Scott Allen",
        level: 2,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 215,
        category: 3),
    new CourseModel(
        ID: 10,
        name: "Architecting for Security on AWS",
        author: "Andru Estes",
        level: 2,
        rating: 2.5,
        date: DateTime.now(),
        numberComment: 545,
        category: 4),
    new CourseModel(
        ID: 11,
        name: "Python: The Big Picture",
        author: "Bryan Hansen",
        level: 2,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 321,
        category: 3),
    new CourseModel(
        ID: 12,
        name: "Programming with R",
        author: "Dustin Schultz",
        level: 2,
        rating: 5,
        date: DateTime.now(),
        numberComment: 313,
        category: 4),
    new CourseModel(
        ID: 13,
        name: "Malware Analysis: Identifying and Defeating",
        author: "Adam Bertram",
        level: 2,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 211,
        category: 2),
    new CourseModel(
        ID: 14,
        name: "Creating Security Baseline in Microsoft",
        author: "Hansen Eames",
        level: 2,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 215,
        category: 3),
    new CourseModel(
        ID: 15,
        name: "Python for Data Analysts",
        author: "Hansen",
        level: 2,
        rating: 3.5,
        date: DateTime.now(),
        numberComment: 111,
        category: 2),
  ];
  void setBookmark(int id, bool b) {
    couserList.firstWhere((element) => element.ID == id).bookmark = b;
    notifyListeners();
  }
}
